### ISSUE TITLE
Update fogbow-cli installation page with the fogbow-manager dependencies information

### ISSUE THREAD

**Issue by eduardolfalcao** [fogbow/fogbowcloud.org#7]
The current procedures give the following error: [ERROR] Failed to execute goal on project fogbow-cli: Could not resolve dependencies for project fogbow-cli:fogbow-cli:jar:0.0.1-SNAPSHOT: Could not find artifact org.fogbowcloud:manager:jar:0.0.1-SNAPSHOT in local (file:///x/y/z/fogbow-cli-master/.m2) -> [Help 1]

**Comment by eduardolfalcao** [comment]
It is also good to make it explicit in the documentation that the user should go to the bin folder to run the commands.

**Comment by abmargb** [comment]
shouldn't this CLI be path agnostic? i.e. it can be executed from anywhere?

**Comment by eduardolfalcao** [comment]
@abmargb this happened because I installed the cli from git, and not from deb (@fgan1 told me this now)
